/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpingo;

/**
 *
 * @author Lokesh Chandra
 */
public class Admin_Block extends javax.swing.JFrame {

    /**
     * Creates new form Admin_Block
     */
    public Admin_Block() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        deladmin = new java.awt.Button();
        close = new java.awt.Button();
        addadmin = new java.awt.Button();
        updateadmin = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ink Free", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Admin Management");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, -1, -1));

        deladmin.setBackground(new java.awt.Color(255, 255, 255));
        deladmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        deladmin.setForeground(new java.awt.Color(255, 102, 0));
        deladmin.setLabel("Delete Admin");
        deladmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deladminActionPerformed(evt);
            }
        });
        jPanel1.add(deladmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 320, 390, 30));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 102, 0));
        close.setLabel("Logout");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 510, 160, 30));

        addadmin.setBackground(new java.awt.Color(255, 255, 255));
        addadmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        addadmin.setForeground(new java.awt.Color(255, 102, 0));
        addadmin.setLabel("Add Admin");
        addadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addadminActionPerformed(evt);
            }
        });
        jPanel1.add(addadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 250, 390, 30));

        updateadmin.setBackground(new java.awt.Color(255, 255, 255));
        updateadmin.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        updateadmin.setForeground(new java.awt.Color(255, 102, 0));
        updateadmin.setLabel("Update Admin");
        updateadmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateadminActionPerformed(evt);
            }
        });
        jPanel1.add(updateadmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, 390, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 0, 530, 660));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/helpingo/images/milobaba.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 350, 520));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 660));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addadminActionPerformed
        // TODO add your handling code here:
        Add_admin addm = new Add_admin();
        addm.setVisible(true);
        dispose();
    }//GEN-LAST:event_addadminActionPerformed

    private void deladminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deladminActionPerformed
        // TODO add your handling code here:
        Del_Admin da = new Del_Admin();
        da.setVisible(true);
        dispose();
    }//GEN-LAST:event_deladminActionPerformed

    private void updateadminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateadminActionPerformed
        // TODO add your handling code here:
        Update_Admin ua = new Update_Admin();
        ua.setVisible(true);
        dispose();
    }//GEN-LAST:event_updateadminActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        SuperUser su = new SuperUser();
        su.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin_Block.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin_Block.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin_Block.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin_Block.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin_Block().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button addadmin;
    private java.awt.Button close;
    private java.awt.Button deladmin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private java.awt.Button updateadmin;
    // End of variables declaration//GEN-END:variables
}
