/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package helpingo;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Lokesh Chandra
 */
public class Update_Admin extends javax.swing.JFrame {

    /**
     * Creates new form Update_Admin
     */
    public Update_Admin() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        username = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        close = new java.awt.Button();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JPasswordField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        fname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel8 = new javax.swing.JLabel();
        mname = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel10 = new javax.swing.JLabel();
        lname = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        region = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        getdetails = new java.awt.Button();
        update = new java.awt.Button();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 102, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setFont(new java.awt.Font("Ink Free", 1, 48)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Update Admin");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 340, 70));
        jPanel1.add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 270, 20));

        username.setBackground(new java.awt.Color(255, 102, 0));
        username.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        username.setForeground(new java.awt.Color(255, 255, 255));
        username.setBorder(null);
        jPanel1.add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 250, 40));

        jLabel12.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username :");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 140, 40));

        close.setBackground(new java.awt.Color(255, 255, 255));
        close.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        close.setForeground(new java.awt.Color(255, 102, 0));
        close.setLabel("Back");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });
        jPanel1.add(close, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 570, 100, 30));

        jLabel6.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Password :");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 130, 40));

        password.setBackground(new java.awt.Color(255, 102, 0));
        password.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        password.setForeground(new java.awt.Color(255, 255, 255));
        password.setBorder(null);
        jPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 230, 270, 20));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 270, 20));

        jLabel9.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("First Name :");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 150, 40));

        fname.setBackground(new java.awt.Color(255, 102, 0));
        fname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        fname.setForeground(new java.awt.Color(255, 255, 255));
        fname.setBorder(null);
        jPanel1.add(fname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 280, 250, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 320, 270, 20));

        jLabel8.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Middle Name :");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 350, 170, 40));

        mname.setBackground(new java.awt.Color(255, 102, 0));
        mname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        mname.setForeground(new java.awt.Color(255, 255, 255));
        mname.setBorder(null);
        jPanel1.add(mname, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 350, 250, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 390, 270, 20));

        jLabel10.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Last Name :");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 160, 40));

        lname.setBackground(new java.awt.Color(255, 102, 0));
        lname.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        lname.setForeground(new java.awt.Color(255, 255, 255));
        lname.setBorder(null);
        jPanel1.add(lname, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 420, 250, 40));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 460, 270, 20));

        jLabel11.setFont(new java.awt.Font("Ink Free", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Region :");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 490, 100, 40));

        region.setBackground(new java.awt.Color(255, 102, 0));
        region.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        region.setForeground(new java.awt.Color(255, 255, 255));
        region.setBorder(null);
        jPanel1.add(region, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 490, 250, 40));
        jPanel1.add(jSeparator6, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, 270, 20));

        getdetails.setBackground(new java.awt.Color(255, 255, 255));
        getdetails.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        getdetails.setForeground(new java.awt.Color(255, 102, 0));
        getdetails.setLabel("Get Details");
        getdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                getdetailsActionPerformed(evt);
            }
        });
        jPanel1.add(getdetails, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 130, 30));

        update.setBackground(new java.awt.Color(255, 255, 255));
        update.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        update.setForeground(new java.awt.Color(255, 102, 0));
        update.setLabel("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });
        jPanel1.add(update, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 570, 130, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1040, 640));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
         Admin_Block ab = new Admin_Block();
        ab.setVisible(true);
        dispose();
    }//GEN-LAST:event_closeActionPerformed

    private void getdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_getdetailsActionPerformed
        try {
            // TODO add your handling code here:
            username.setEditable(false);
            String uname = username.getText();
            String pas=null,fnm=null,mnm=null,lnm=null,rgn=null;
            String sql = "SELECT * FROM admin where user_handle='"+uname+"'";
            
            MysqlConnection msql = new MysqlConnection();
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
            
            while(rs.next())
            {
                pas = rs.getString("password");
                fnm = rs.getString("first_name");
                mnm = rs.getString("middle_name");
                lnm = rs.getString("last_name");
                rgn = rs.getString("region");
                
            }
            password.setText(pas);
            fname.setText(fnm);
            mname.setText(mnm);
            lname.setText(lnm);
            region.setText(rgn);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_getdetailsActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        try {
            // TODO add your handling code here:
             String pas=null,fnm=null,mnm=null,lnm=null,rgn=null;
            String uname = username.getText();
            
            pas = password.getText();
            fnm= fname.getText();
            mnm = mname.getText();
            lnm = lname.getText();
            rgn = region.getText();
            
            String sql = "update admin set password='"+pas+"', first_name='"+fnm+"', middle_name='"+mnm+"', last_name='"+lnm+"', region='"+rgn+"' where user_handle='"+uname+"'";
            MysqlConnection msql = new MysqlConnection();
            PreparedStatement pstmt = msql.conn.prepareStatement(sql);
            int i = pstmt.executeUpdate();
            
            if(i>0)
                JOptionPane.showMessageDialog(null, "Sucessfully Updated");
            else
                JOptionPane.showMessageDialog(null, "Not Updated");
            
            
        } catch (SQLException ex) {
            Logger.getLogger(Update_Admin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_updateActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Update_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Update_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Update_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Update_Admin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Update_Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button close;
    private javax.swing.JTextField fname;
    private java.awt.Button getdetails;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JTextField lname;
    private javax.swing.JTextField mname;
    private javax.swing.JPasswordField password;
    private javax.swing.JTextField region;
    private java.awt.Button update;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
